<?php
/**
 * DefaultApiTest
 * PHP version 8.1
 *
 * @package  kruegge82\DHLTrack
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DHL Parcel DE Shipment Tracking
 *
 * Note: The API type is a RESTful Webservice and the Tracking API works exclusively with the GET method. Please have a look to the WADL in Download Section.
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace kruegge82\DHLTrack\Test\Api;

use kruegge82\DHLTrack\Configuration;
use kruegge82\DHLTrack\ApiException;
use kruegge82\DHLTrack\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @package  kruegge82\DHLTrack
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for placeholderSeeWADLAndTestsuiteGet
     *
     * .
     *
     */
    public function testPlaceholderSeeWADLAndTestsuiteGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
